"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import dj_database_url 
from datetime import timedelta
from pathlib import Path
import os
import re
import logging
import cloudinary
from cloudinary import uploader
from cloudinary import api
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO, format='[%(asctime)s] - [%(levelname)s] : %(message)s')
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")
OFFLINE = os.getenv("OFFLINE", "False").lower() in ("true", "1", "yes")
logger.info(f"Debug: {DEBUG}")
logger.info(f"OFFLINE: {OFFLINE}")


ALLOWED_HOSTS = os.environ["ALLOWED_HOSTS"].split(", ")
BLOG_ORIGINS = os.environ["BLOG_ORIGINS"].split(", ")

# Fetch the regex string from environment variables
CORS_REGEX_STR = os.getenv('BLOG_REGEX')

if CORS_REGEX_STR:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        rf"{CORS_REGEX_STR}",
    ]

# Allow requests from the frontend
CSRF_TRUSTED_ORIGINS = BLOG_ORIGINS + ["https://*-uyonohs-projects.vercel.app"]

CORS_ALLOWED_ORIGINS = BLOG_ORIGINS

# Optional: allow credentials for session auth
CORS_ALLOW_CREDENTIALS = True

# Application definition
INSTALLED_APPS = []
if not OFFLINE:
    # Cloudinary
    INSTALLED_APPS += [
    'cloudinary_storage',
    'cloudinary',
    ]

INSTALLED_APPS += [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',  
    # Your app
    'users',
    'blog_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Comment out DATABASE_URL from .env in offline mode, else it will override 
if OFFLINE:
    DATABASE_URL = os.getenv("OFFLINE_DATABASE_URL")
else:
    DATABASE_URL = os.getenv("DATABASE_URL")
DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600
    )
}
logger.info(f"Database URL: {DATABASE_URL}")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'SCOPE': ['email'],
    },
}

SITE_ID = 1 

REST_USE_JWT = True  # Use JWT for dj-rest-auth

# Django Rest Framework settings for JWT authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}

# For simple JWT settings
SIMPLE_JWT = {
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    # "ALGORITHM": "HS256",
    # "SIGNING_KEY": os.getenv("JWT_SECRET_KEY"),
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static', # Example: Look for static files in a 'static' folder at the project root
# ]

# Media files (image uploads, videos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not OFFLINE:
    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET
    )
    
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # STATICFILES_STORAGE  = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookies

REFRESH_COOKIE_NAME = "ub_refresh_token"  # used in views
REFRESH_COOKIE_SECURE = True  # True in production (requires HTTPS)
REFRESH_COOKIE_SAMESITE = "None"  # None -> allow cross-site, set Secure=True
REFRESH_COOKIE_HTTPONLY = True
REFRESH_COOKIE_PATH = "/auth/"   

CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN" # Default, but good to be explicit
CSRF_COOKIE_SAMESITE = 'Lax' # Or 'None' if more strict cross-site sharing, but requires secure cookie

# For production with cross-site cookies, CSRF_COOKIE_SECURE and CSRF_COOKIE_SAMESITE
# are critical.
if not DEBUG:
    CSRF_COOKIE_SECURE = True   # <--- CRITICAL: Must be True for SameSite='None'
    CSRF_COOKIE_SAMESITE = 'None' # <--- CHANGE THIS: Allow cross-site sending

    # Session settings for cross-site access
    SESSION_COOKIE_SECURE = True   # <--- CRITICAL: Must be True for SameSite='None'
    SESSION_COOKIE_SAMESITE = 'None' # <--- CHANGE THIS: Allow cross-site sending
