# Generated by Django 5.1.7 on 2025-04-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_like_created_at_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
