# Generated by Django 5.2.1 on 2025-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_alter_post_options_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
