# Generated by Django 5.2.1 on 2025-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0011_topic_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog_api.topic'),
        ),
    ]
