# Generated by Django 5.2.1 on 2026-01-16 08:42

import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0017_alter_comment_author_alter_like_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-updated_at'], name='blog_api_po_updated_d09779_idx'),
        ),
    ]
