# Generated by Django 5.2.1 on 2026-01-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0018_post_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX post_search_vector_idx
            ON blog_api_post
            USING GIN (search_vector);
            """,
            reverse_sql="""
            DROP INDEX post_search_vector_idx
            """
        ),
    ]
